controllers/CartController.php
<?php

namespace app\controllers;

use Yii;
use app\models\IkeaOrderForm;
use app\models\DeliveryForm;
use app\models\Order;
use app\models\OrderItem;
use app\models\Item;
use yii\helpers\Url;
use app\models\Utilities;
use yii\web\NotFoundHttpException;
use yii\helpers\VarDumper;

class CartController extends DefaultController
{

  public function actionIndex()
  {

    $model=new IkeaOrderForm();

    if (!empty($_POST['items'])) {
      foreach ($_POST['items'] as $item=>$qty) {
        $ikeaItem=\Yii::$app->cart->getPositionById($item);
        if ($ikeaItem && $qty < 1000)
          \Yii::$app->cart->update($ikeaItem, $qty);
      }
      $this->refresh();
    }
    return $this->render('index', [
        'model'=>$model,
    ]);
  }

  /**
   * Delete item from shopping card
   */
  public function actionDelete()
  {


    $res['code']='404';

    $ikeaItem=\Yii::$app->cart->getPositionById($_POST['id']);
    if ($ikeaItem) {
      \Yii::$app->cart->remove($ikeaItem);
      $res['code']=200;
      //$res['count'] = Utilities::Currency(\Yii::$app->cart->getItemsCount(), false);
      $res['cost']=Utilities::Currency(\Yii::$app->cart->cost);
      $res['cart_html']=\app\components\ShoppingCartWidget::widget();
    }
    echo json_encode($res);

    Yii::$app->end();
  }

  public function actionStop()
  {
    return $this->render('stop');
  }

  public function actionCheckout()
  {
    $this->redirect(Url::toRoute('cart/stop'));

    if (Yii::$app->cart->getIsEmpty())
      $this->redirect('/cart');

    $model=new DeliveryForm();
    /*if ($model->load(Yii::$app->request->post())) {
      if ($model->validate()) {
        $order=new Order();
        $order->user_id=Yii::$app->user->id;
        $order->customer_name=$model->name;
        $order->customer_email=$model->email;
        $order->customer_phone=$model->phone;
        $order->address=$model->address;
        $order->note=$model->note;
        $order->status=Order::STATUS_ADDED;
        $order->total_due_bel=(float)Utilities::currencyDenom(\Yii::$app->cart->cost, false, false);
        $order->save();

        $total_due_rus=0;

        foreach (\Yii::$app->cart->getPositions() as $item) {

          $orderItem=new OrderItem();
          $orderItem->order_id=$order->id;
          $orderItem->item_id=$item->id;
          $orderItem->number=$item->number;
          $orderItem->short_description=$item->short_description;
          $orderItem->rus_price=$item->rus_price;
          $orderItem->bel_price=(float)Utilities::currencyDenom($item->getPrice(), false, false);
          $orderItem->total_bel_price=(float)Utilities::currencyDenom($item->getCost(), false, false);
          $orderItem->title=$item->title;
          $orderItem->ikea_url_slug=$item->ikea_url_slug;
          $orderItem->qty=$item->getQuantity();
          $orderItem->total_rus_price=$item->rus_price * $item->getQuantity();
          $orderItem->save();

          $total_due_rus+=$orderItem->rus_price;

        }

        $order->total_due_rus=$total_due_rus;
        $order->save();
        \Yii::$app->cart->removeAll();

        $this->redirect(Url::toRoute('cart/thank-you'));
      }
    }*/
    return $this->render('checkout', [
        'model'=>$model,
    ]);
  }

  public function actionThankYou()
  {
    return $this->render('thankYou', [
    ]);
  }

  /**
   * Clear shopping card
   */
  public function actionClear()
  {
    \Yii::$app->cart->removeAll();
    $this->redirect(Url::toRoute('cart/index'));
  }

  public function actionAdd()
  {
    $res['code']='404';
    $res['cart_qty']=0;
    $res['cart_total_price']=0;

    $id=Yii::$app->getRequest()->post('id');
    $qty=(int)Yii::$app->getRequest()->post('qty');
    $item=Item::findOne(['id'=>$id]);
    if ($item && $qty < 1000) {
      $res['code']='200';
      \Yii::$app->cart->put($item, $qty);

      $res['cart_qty']=\Yii::$app->cart->getCount();
      $res['cart_total_price']=Utilities::Currency(\Yii::$app->cart->getCost());
      $res['cart_total_items']=\Yii::$app->cart->getCount();
      $res['cart_html']=\app\components\ShoppingCartWidget::widget();
    }

    return json_encode($res);
  }

}

views/cart/checkout.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\widgets\ActiveForm */
/* @var $model app\models\LoginForm */

$this->title = 'Адрес доставки';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Пожалуйста, заполните поля для оформления заказа</p>

    <?php $form = ActiveForm::begin([
        'id' => 'delivery-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-4\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-2 control-label'],
        ],
    ]); ?>

    <?= $form->field($model, 'name') ?>
    <?= $form->field($model, 'phone') ?>
    <?= $form->field($model, 'email') ?>
    <?= $form->field($model, 'address')->textarea() ?>
    <?= $form->field($model, 'note')->textarea() ?>

    <div class="form-group">
        <div class="col-lg-offset-2 col-lg-11">
            <?= Html::submitButton('Оформить заказ', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-2 text-muted" >
       После оформления заказа с вами свяжется менеджер.
    </div>
</div>

views/cart/index.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\widgets\ActiveForm */
/* @var $model app\models\ContactForm */

$this->title = 'Заказ';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>


    <?php else: ?>

        <p>
            Если у вас есть вопросы или предложения, напишите нам! 
        </p>



    <?php endif; ?>
    <?php if (!Yii::$app->cart->getIsEmpty()): ?>

        <h2>Ваша корзина</h2>
        <div class="bs-component">
            <?php
            $form = ActiveForm::begin([
                        'id' => 'cart-form',
                    ])
            ?>
            <table class="table table-striped table-hover ">
                <thead>
                    <tr>
                        <th>#</th><th>Артикул</th><th>Картинка</th>
                        <th>Название</th><th>Краткое описание</th><th>Кол-во в упаковке</th>
                        <th>Цена бел.руб</th><th>Кол-во</th><th>Сумма</th><th></th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $i = 1;
                    foreach (\Yii::$app->cart->getPositions() as $ikeaItem):
                        ?>
                        <tr>
                            <td><?php echo $i ?></td>
                            <td><?php echo $ikeaItem->number ?></td>
                            <td style=""><img width="100" src="http://www.ikea.com/<?php echo $ikeaItem->image_uri ?>"></td>
                            <td><?php echo $ikeaItem->title ?></td>
                            <td><?php echo $ikeaItem->short_description ?></td>
                            <td><?php echo isset($ikeaItem->qty_in_pack) ? $ikeaItem->qty_in_pack : '' ?></td>
                            <td><?php echo app\models\Utilities::Currency($ikeaItem->getPrice()) ?> </td>
                            <td><input type="text" id="item_<?php echo $ikeaItem->id ?>" name="items[<?php echo $ikeaItem->id ?>]" value="<?php echo $ikeaItem->getQuantity() ?>" class="qty" size="3" maxlength="10"></td>
                            <td><?php echo app\models\Utilities::Currency($ikeaItem->getCost()) ?></td>
                            <td style="text-align: right"><a href="<?php echo \yii\helpers\Url::toRoute('/cart/delete'); ?>" data-item="<?php echo $ikeaItem->id ?>" class="delete">Удалить</a></td>
                        </tr>
                        <?php
                        $i++;
                    endforeach;
                    ?>
                    <tr>
                        <td colspan="7"><a href="<?php echo \yii\helpers\Url::toRoute('/cart/clear'); ?>">Очистить корзину</a></td>
                        <td colspan="3" style="text-align: right; font-weight: bold">Итого: <span class="cart-cost"><?php echo app\models\Utilities::Currency(\Yii::$app->cart->cost, false) ?></span> бел. рублей</td>
                    </tr>
                    <tr>
                        <td colspan="9">
                            <?= Html::submitButton('Обновить корзину', ['class' => 'btn btn-primary']) ?></td>
                        <td colspan=""><a href="<?php echo \yii\helpers\Url::toRoute('/cart/checkout'); ?>" class="btn btn-primary" style="text-align: right;">Перейти к оформлению</a></td>
                    </tr>                    
                </tbody>
            </table> 

            <?php ActiveForm::end() ?>
        <?php else: ?>


        </div>    
    <?php endif; ?>


</div>

views/cart/index_old.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\widgets\ActiveForm */
/* @var $model app\models\ContactForm */

$this->title = 'Заказ';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>


    <?php else: ?>

        <p>
            Если у вас есть вопросы или предложения, напишите нам! 
        </p>

        <div class="row">
            <div class="col-lg-5">
                <?php $form = ActiveForm::begin(['id' => 'ikea-order-form']); ?>
              <div class="input-group">
                      <?php
                      echo $form->field($model, 'ikea_number_or_url', [
                          'template' => "{input}\n{hint}"
                      ])
                      ?>
                    <span class="input-group-btn">
                        <?= Html::submitButton('Добавить товар', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </span>
                </div>
<?php    echo Html::error($model,'ikea_number_or_url', ['class' => 'help-block']); //error?>                
                <?php ActiveForm::end(); ?>
            </div>
        </div>

    <?php endif; ?>
        <?php if (!Yii::$app->cart->getIsEmpty()):?>
        
            <h2>Ваша корзина</h2>

        
        


<div class="bs-component">

    
    <?php
    $form = ActiveForm::begin([
                'id' => 'cart-form',
            ])
    ?>
            <table class="table table-striped table-hover ">
                <thead>
                    <tr>
                        <th>#</th><th>Артикул</th><th>Картинка</th>
                        <th>Название</th><th>Краткое описание</th><th>Средне описание</th><th>Кол-во в упаковке</th>
                        <th>Цена RUB</th><th>Цена бел.руб</th><th>Кол-во</th><th>Сумма</th><th></th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $i=1;
                    foreach (\Yii::$app->cart->getPositions() as $ikeaItem):?>
                        <tr>
                            <td><?php echo $i?></td>
                            <td><?php echo $ikeaItem->number ?></td>
                            <td><img src="http://www.ikea.com/<?php echo $ikeaItem->small_img_src ?>"></td>
                            <td><?php echo $ikeaItem->title ?></td>
                            <td><?php echo $ikeaItem->short_description ?></td>
                            <td><?php echo $ikeaItem->middle_description ?></td>
                            <td><?php echo $ikeaItem->package_quantity ?></td>
                            <td><?php echo $ikeaItem->rus_price_total ?> rub</td>
                            <td><?php echo $ikeaItem->bel_price_total ?> б.р.</td>
                            <td><input type="text" id="item_<?php echo $ikeaItem->number?>" name="items[<?php echo $ikeaItem->number?>]" value="<?php echo $ikeaItem->getQuantity()?>" class="qty" size="3" maxlength="10"></td>
                            <td><?php echo $ikeaItem->getCost() ?></td>
                            <td><a href="<?php echo \yii\helpers\Url::toRoute('/cart/delete');?>" data-item="<?php echo $ikeaItem->number?>" class="delete">Удалить</a></td>
                        </tr>
                    <?php 
                    $i++;
                    endforeach;?>
                    <tr>
                        <td colspan="7"><a href="<?php echo \yii\helpers\Url::toRoute('/cart/clear');?>">Очистить корзину</a></td>
                        <td colspan="5" style="text-align: right; font-weight: bold">Итого: <span class="cart-cost"><?php echo \Yii::$app->cart->cost?></span> бел. рублей</td>
                    </tr>
                    <tr>
                        <td colspan="11">
                             <?= Html::submitButton('Обновить корзину', ['class' => 'btn btn-primary']) ?></td>
                        <td colspan=""><a href="<?php echo \yii\helpers\Url::toRoute('/cart/checkout');?>" class="btn btn-primary" style="text-align: right;">Перейти к оформлению</a></td>
                    </tr>                    
                </tbody>
            </table> 

    <?php  ActiveForm::end() ?>
            <?php else: ?>
    
    
        </div>    
    <?php endif;?>


</div>

views/cart/thankYou.php
<h1>Спасибо за заказ!</h1>
<h3>Ждите подтверждения на email.</h3>
<h3><a href="/item/index">Продолжить покупки</a></h3>